# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "rgunti"
    reviewers:
      - "rgunti"
    labels:
      - "dependencies"
      - "pnpm"
    commit-message:
      prefix: "deps(pnpm)"
    ignore:
      # Ignore all major updates
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-eslint/*"
          - "@angular-devkit/*"
      ng-icons:
        patterns:
          - "@ng-icons/*"
      dev-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "rgunti"
    reviewers:
      - "rgunti"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "deps(docker)"
    ignore:
      # Ignore all major updates
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "rgunti"
    reviewers:
      - "rgunti"
    labels:
      - "dependencies"
      - "gh-actions"
    commit-message:
      prefix: "deps(gh-actions)"
    groups:
      actions:
        patterns:
          - "actions/*"
      docker:
        patterns:
          - "docker/*"
